name: Maven CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Build project with Maven
      run: mvn clean package -DskipTests
      
    - name: push changes to remote
      run: |
        git config user.name "alejandromorenobea"
        git config user.email "alejandromorenobea@fp.iesromerovargas.com"
        git add -f webapp/target/*.war
        git commit -m "From Action GH"
        git push
        
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true 
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/maven-app:test,${{ secrets.DOCKERHUB_USERNAME }}/maven-app:latest


    - name: multiple command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOSTNAME }}
        username: ${{ secrets.USER_NAME }}
        key: ${{ secrets.AWS_PRIVATE_KEY }}
        port: 22  # ${{ secrets.PORT }}
        script: |
            docker stop web1 && docker rm web1
            docker run -d -p 80:80 --name web1 alejandromorenobea/CETI-Ejercicio
